### ISSUE TITLE
Crashing on Android 14 device

### ISSUE THREAD

**Issue by crashfiredeep** [developermypos/myPOS-SDK-Android#26]
When click on connect device button as given in sample, app crashes with following crash error 

Crash error: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

Log:

AndroidRuntime            E  FATAL EXCEPTION: main
                             Process: com.example.mypospal_test, PID: 21412
                             java.lang.SecurityException: com.example.mypospal_test: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                             	at android.os.Parcel.createExceptionOrNull(Parcel.java:3071)
                             	at android.os.Parcel.createException(Parcel.java:3055)
                             	at android.os.Parcel.readException(Parcel.java:3038)
                             	at android.os.Parcel.readException(Parcel.java:2980)
                             	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6352)
                             	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1876)
                             	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1811)
                             	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1799)
                             	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
                             	at com.mypos.slavesdk.PaxUsbConnectionHandler.connect(PaxUsbConnectionHandler.java:102)
                             	at com.mypos.slavesdk.BaseCommand.reconectLoop(BaseCommand.java:115)
                             	at com.mypos.slavesdk.BaseCommand.access$100(BaseCommand.java:16)
                             	at com.mypos.slavesdk.BaseCommand$2.run(BaseCommand.java:92)
                             	at android.os.Handler.handleCallback(Handler.java:1013)
                             	at android.os.Handler.dispatchMessage(Handler.java:101)
                             	at android.os.Looper.loopOnce(Looper.java:226)
                             	at android.os.Looper.loop(Looper.java:328)
                             	at android.app.ActivityThread.main(ActivityThread.java:9193)
                             	at java.lang.reflect.Method.invoke(Native Method)
                             	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
                             	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                             Caused by: android.os.RemoteException: Remote stack trace:
                             	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:15719)
                             	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12266)
                             	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3128)
                             	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3224)
                             	at android.os.Binder.execTransactInternal(Binder.java:1405)
CustomActivityOnCrash     E  App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
                             java.lang.SecurityException: com.example.mypospal_test: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                             	at android.os.Parcel.createExceptionOrNull(Parcel.java:3071)
                             	at android.os.Parcel.createException(Parcel.java:3055)
                             	at android.os.Parcel.readException(Parcel.java:3038)
                             	at android.os.Parcel.readException(Parcel.java:2980)
                             	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6352)
                             	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1876)
                             	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1811)
                             	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1799)
                             	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
                             	at com.mypos.slavesdk.PaxUsbConnectionHandler.connect(PaxUsbConnectionHandler.java:102)
                             	at com.mypos.slavesdk.BaseCommand.reconectLoop(BaseCommand.java:115)
                             	at com.mypos.slavesdk.BaseCommand.access$100(BaseCommand.java:16)
                             	at com.mypos.slavesdk.BaseCommand$2.run(BaseCommand.java:92)
                             	at android.os.Handler.handleCallback(Handler.java:1013)
                             	at android.os.Handler.dispatchMessage(Handler.java:101)
                             	at android.os.Looper.loopOnce(Looper.java:226)
                             	at android.os.Looper.loop(Looper.java:328)
                             	at android.app.ActivityThread.main(ActivityThread.java:9193)
                             	at java.lang.reflect.Method.invoke(Native Method)
                             	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
                             	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                             Caused by: android.os.RemoteException: Remote stack trace:
                             	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:15719)
                             	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12266)
                             	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3128)
                             	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3224)
                             	at android.os.Binder.execTransactInternal(Binder.java:1405)

**Comment by StiliyanKovachev** [comment]
I just updated to the latest .aar file. please pull the changes and try again.

**Comment by crashfiredeep** [comment]
> I just updated to the latest .aar file. please pull the changes and try again.
@StiliyanKovachev 


Still not working getting same error, did you added one of the below in register receiver for andorid 14 issues?
RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED

**Comment by StiliyanKovachev** [comment]
Can you please test [this sdk version](https://f.mypos.com/index.php/s/SKHWLCiPptNd9d6) . Just replace it in your slavesdk directory. Thanks.

**Comment by crashfiredeep** [comment]
> Can you please test [this sdk version](https://f.mypos.com/index.php/s/SKHWLCiPptNd9d6) . Just replace it in your slavesdk directory. Thanks.

Now worked!!! and does not crashed. can close this issue now.
Thanks @StiliyanKovachev

**Comment by StiliyanKovachev** [comment]
thanks
