### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by crashfiredeep** [developermypos/myPOS-SDK-Android#27]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.usb.UsbDeviceConnection.controlTransfer(int, int, int, int, byte[], int, int)' on a null object reference
       at com.mypos.slavesdk.serial.CdcAcmSerialDriver$CdcAcmSerialPort.sendAcmControlMessage(CdcAcmSerialDriver.java:190)
       at com.mypos.slavesdk.serial.CdcAcmSerialDriver$CdcAcmSerialPort.setParameters(CdcAcmSerialDriver.java:239)
       at com.mypos.slavesdk.XgdUsbConnectionHandler$2.run(XgdUsbConnectionHandler.java:154)
       at java.lang.Thread.run(Thread.java:764)

**Comment by StiliyanKovachev** [comment]
duplicated issue : https://github.com/developermypos/myPOS-SDK-Android/issues/25

if your devices also have no cash register mode provide serial numbers and I will update their software packages
